### ISSUE TITLE
Flips are glitched when uploaded to my wordpress website

### ISSUE THREAD

**Issue by mapavia** [kbwood/flightboard#1]
The code works great and I got it working on a simple html file. But when I upload it to my wordpress theme it looks weird. I know this will not be easy to fix but I was wondering what I could investigate in the code in order to check which one is causing this error? I tried looking at the jquery file but I have no experience with this so I was hoping for a bit of help. Attached is the screenshot of the glitch.
![flipboard](https://user-images.githubusercontent.com/17270252/100820256-f6354f80-34a1-11eb-83a4-45f91dc51f0c.PNG)

**Comment by kbwood** [comment]
It looks like a screen rendering issue - a line is stretched across the entire letter space - but I can't tell from a screenshot.

**Comment by cotasson** [comment]
Hello Keith, 

Your plugin is great  ! There are other "flight board" projects around, but yours is the best. 
I would really like to have it implemented on my next project. 
I come across the same problem as @mapavia . 

See for yourself : better than a screenshot. 
Original (and working) version : https://tiny-ouzoum.com/wp-content/themes/understrap-child-master/flightboard2/flightBoardBasic.html

Well, I just "updated" the jQuery library. But still, it works. 

The buggy version : 
https://tiny-ouzoum.com/

Here's the glitch ! 
Granted, the scripts are not in the <head> part here, but even when I do it this way, it doesn't work any better. 

I changed themes, same problem. 

Any idea ?

**Comment by kbwood** [comment]
The problem arises from the `max-width: 100%` style applied to images in `child-theme.min.css`. Without that it looks fine! (I don't know why.)

**Comment by cotasson** [comment]
Thank you  ! It works !

**Comment by cyrussutaria** [comment]
Does anyone know whats the highest version of jquery this would work with?
